# manager/cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', '${_CLUSTER}', '--zone=${_ZONE}', '--project=${PROJECT_ID}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - |
    ACCESS_TOKEN=$(gcloud auth print-access-token --impersonate-service-account=584438132152@cloudbuild.gserviceaccount.com)
    kubectl --token="$ACCESS_TOKEN" apply -f manager/manager-deployment.yaml
