# manager/cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_CLUSTER}" --zone="${_ZONE}" --project="${PROJECT_ID}"
    kubectl apply -f manager/manager-deployment.yaml