apiVersion: apps/v1
kind: Deployment
metadata:

  name: "{{RESOURCE_NAME}}"
  labels:
    app: "{{BASE_NAME}}"

    version: "{{APP_VERSION}}"
spec:
  replicas: 1
  selector:
    matchLabels:

      app: "{{BASE_NAME}}"

      version: "{{APP_VERSION}}"
  template:
    metadata:
      labels:

        app: "{{BASE_NAME}}"


        version: "{{APP_VERSION}}"
    spec:
      containers:
      - name: "{{APP_NAME}}"
        image: "{{IMAGE_NAME}}"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        env:
        - name: "WEATHER_API_KEY"
          value: "<YOUR_WEATHER_API_KEY>"
      
