apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:

  name: "{{INGRESS_NAME}}"

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:

  - host: "{{APP_NAME}}.{{DOMAIN_NAME}}"

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:

            name: "{{RESOURCE_NAME}}"

            port:
              number: 80
  tls:
  - hosts:

    - "{{APP_NAME}}.{{DOMAIN_NAME}}"
    secretName: "{{BASE_NAME}}-tls"


