apiVersion: v1
kind: Service
metadata:

  name: "{{RESOURCE_NAME}}"
spec:
  type: ClusterIP
  selector:
    app: "{{BASE_NAME}}"
    version: "{{APP_VERSION}}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
