# .github/workflows/deploy.yml

name: Build and Deploy Manager

on:
  push:
    branches:
      - main
      - deploy

env:
  # Define environment variables that are not secret
  IMAGE_NAME: gcs-k8s-deployment-manager
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required to authenticate to GCP with Workload Identity Federation


    steps:
    - name: "DEBUG: Print repository name"
      run: echo "The exact repository name is ${{ github.repository }}"

    - name: Checkout code
      uses: actions/checkout@v3

    # 1. Authenticate to Google Cloud using Workload Identity Federation (most secure)
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: "VERIFY AUTH: Display authenticated user"
      run: gcloud auth list

    - name: Docker Login
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}

    # 4. Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     -t ${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest \
                     ./manager

    # 5. Push the Docker image to the registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest

    # 6. Deploy to Google Kubernetes Engine
    - name: Deploy via gcs-k8s-deployment-manager
      run: |
        # First, substitute the placeholder values in the deployment manifest
        sed -i'' -e 's|<MANAGER_IMAGE_REGISTRY_URL>|${{ secrets.MANAGER_IMAGE_REGISTRY_URL }}|g' ./manager/manager-deployment.yaml
        sed -i'' -e 's|<CONTAINER_REGISTRY_URL>|${{ secrets.CONTAINER_REGISTRY_URL }}|g' ./manager/manager-deployment.yaml
        sed -i'' -e 's|<YOUR_EMAIL_FOR_LETSENCRYPT>|${{ secrets.LETSENCRYPT_EMAIL }}|g' ./manager/manager-deployment.yaml
        sed -i'' -e 's|:latest|:${{ github.sha }}|g' ./manager/manager-deployment.yaml

        # Now, submit the configured file to Cloud Build to apply
        gcloud builds submit . \
          --config=cloudbuild.yaml \
          --substitutions=_ZONE=${{ env.GKE_CLUSTER_ZONE }},_CLUSTER=${{ env.GKE_CLUSTER_NAME }}

